rvm:
  - 2.0.0
language: ruby
gemfile:
  - Gemfile
before_script: 
  - "export DISPLAY=:99.0"
  - "export CUCUMBER_FORMAT=pretty"
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake db:schema:load"
script:
  - "bundle exec rake --trace"
