rvm:
  - 2.6.2
sudo: false
language: ruby
services:
  - postgresql
before_install:
  - "npm install -g bower"
before_script:
  - RAILS_ENV=test bundle exec rake webdrivers:chromedriver:update
  - export WD_CHROME_PATH=$(which google-chrome-stable)
  - "bundle exec rake db:create db:schema:load bower:install"
addons:
  chrome: stable
  code_climate:
    repo_token: 1a38b5fd0d6270e3deed4fbb8bb641c115ce48f1df47180f921d8b6db5ddd240
