rvm:
  - 1.9.2
  - 1.9.3
language: ruby
gemfile:
  - Gemfile
before_script: 
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "mkdir -p tmp"
script:
  - "bundle exec rake db:test:prepare"
  - "bundle exec rake test"
  - "bundle exec cucumber --format pretty features"
