rvm:
  - 2.6.2
sudo: false
language: ruby
services:
  - postgresql
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - "npm install -g bower"
  - bundle install
  - RAILS_ENV=test bundle exec rake webdrivers:chromedriver:update
before_script:
  - "bundle exec rake db:create db:schema:load bower:install"
addons:
  chrome: stable
  code_climate:
    repo_token: 1a38b5fd0d6270e3deed4fbb8bb641c115ce48f1df47180f921d8b6db5ddd240
