rvm:
  - 1.9.2
  - 1.9.3
language: ruby
gemfile:
  - Gemfile
before_script: 
  - "export DISPLAY=:99.0"
  - "export CUCUMBER_FORMAT=pretty"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "bundle exec rake --trace"
