rvm:
  - 1.9.2
  - 1.9.3
gemfile:
  - Gemfile
before_script: 
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "mkdir -p tmp"
  - "rake db:migrate"
  - "rake test"
  - "cucumber --format pretty features"
script:
  - bundle exec rake travis
