development: &DEV
  adapter: postgresql
  host: localhost
  username: postgres
  database: vellum_development
  pool: <%= ENV['DB_POOL'] || 16 %>

test: &TEST
  adapter: postgresql
  host: localhost
  username: postgres
  database: vellum_test

cucumber:
  <<: *TEST

production:
  <<: *DEV
