development: &DEV
  adapter: postgresql
  host: localhost
  username: postgres
  database: vellum_development

test: &TEST
  adapter: postgresql
  host: localhost
  username: postgres
  database: vellum_test

cucumber:
  <<: *TEST

production:
  <<: *DEV
