# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 0) do

  create_table "relationship_types_templates", :id => false, :force => true do |t|
    t.column "relationship_type_id", :integer
    t.column "template_id",          :integer
  end

end
